<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>


<h3 style="text-align: center;"><b>Школа глубокого обучения ФПМИ МФТИ, осень 2021</b></h3>

## Домашнее задание: библиотека Numpy и линейная алгебра


In [1]:
import numpy as np
import random
import scipy.stats as sps

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [2]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

# Выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?

# ========
# Ваш код здесь
# ========
print(a)
print(b)

[[0.07840104 0.41417758 0.24442886 ... 0.28229813 0.88107917 0.97228311]
 [0.10401634 0.65734939 0.43132868 ... 0.52585215 0.02688908 0.45477814]
 [0.62176153 0.42995278 0.35250008 ... 0.25897096 0.6379807  0.77917658]
 ...
 [0.47788505 0.50518363 0.9337813  ... 0.40603908 0.2345104  0.56277571]
 [0.50588224 0.00130822 0.45047845 ... 0.80715012 0.22462125 0.82760851]
 [0.49033239 0.77489441 0.51333656 ... 0.48030673 0.32060145 0.89510078]]
[[0.65394415 0.38421819 0.71001111 ... 0.20562511 0.06209438 0.47493859]
 [0.10444299 0.68419278 0.90388426 ... 0.09698435 0.88944137 0.43515572]
 [0.39697862 0.1531486  0.21384331 ... 0.33393219 0.77950224 0.03638293]
 ...
 [0.86592109 0.59888262 0.4340037  ... 0.41855881 0.24504356 0.41932436]
 [0.26881709 0.84207813 0.12489999 ... 0.58023966 0.89846143 0.37165351]
 [0.05688855 0.08333169 0.80530184 ... 0.09604793 0.11498313 0.52911949]]


In [3]:
def no_numpy_mult(a, b):
    """  
    a: list of "size" lists, each contains "size" floats --- первая матрица-аргумент
    b: list of "size" lists, each contains "size" floats --- вторая матрица-аргумент
    return c: list of "size" lists, each contains "size" floats --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц без использования функций из пакета numpy
    """
    z = len(a)
    # транспонируем матрицу b, чтобы загнать в zip
    T = [*zip(*b)]
    return [[sum(x * y for x, y in zip(a[r], T[c])) for c in range(z)] for r in range(z)]

In [4]:
def numpy_mult(a, b):
    """  
    a: np.array[size, size] --- первая матрица-аргумент
    b: np.array[size, size] --- вторая матрица-аргумент
    return c: np.array[size, size]       --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц, используя функции из пакета numpy
    """
    return a @ b

In [5]:
%%time
# засечем время работы функции без NumPy
M1 = no_numpy_mult(a, b)

Wall time: 379 ms


In [6]:
%%time
# засечем время работы функции с NumPy
M2 = numpy_mult(a, b)

Wall time: 112 ms


In [7]:
# проверим корректность
assert np.allclose(np.array(M1), M2)

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [8]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.12666048 0.62002784 0.02800914] [0.17411372 0.08680786 0.64825638]


In [9]:
def no_numpy_scalar(v1, v2):
    """  
    a: np.array[, n] --- первая матрица-аргумент длиной n
    b: np.array[, n] --- вторая матрица-аргумент длиной n
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c 

    Реализуйте скалярное умножение векторов, не используя функции из пакета numpy

    """ 
    return sum(a * b for a, b in zip(v1, v2))

In [10]:
def numpy_scalar(v1, v2):
    """  
    a: np.array[, n] --- первая матрица-аргумент
    b: np.array[, n] --- вторая матрица-аргумент
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c 

    Реализуйте скалярное умножение векторов, используя функции из пакета numpy
    """ 
    return np.dot(v1, v2)

In [11]:
%time product_1 = no_numpy_scalar(a,b)
%time product_2 = numpy_scalar(a,b)

# проверим корректность:
assert np.allclose(product_1, product_2)

Wall time: 0 ns
Wall time: 0 ns


Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональных элементов квадратной матрицы. Если таких элементов нет, то вывести `0`. Используйте библиотеку Numpy

In [12]:
def np_diag_2k(a):
    """  
    a: np.array[m, m] --- первая матрица-аргумент
    return c: float   --- сумма элементов массива а, принадлежащих диагонали и являющимися четными

    Функция принимает на вход квадратную матрицу размерностью m x m и возвращает число,
    равное сумме четных диагональных элементов этой квадратной матрицы

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    return np.diag(a)[np.diag(a) % 2 == 0].sum()

In [13]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[4, 4, 4, 6, 1],
       [6, 2, 1, 5, 2],
       [8, 7, 4, 8, 8],
       [1, 6, 6, 7, 8],
       [8, 7, 9, 7, 8]])

In [14]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

Wall time: 0 ns


18

### Задание 4
​
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $(x = (x_1, x_2, \ldots, x_n)$ массива $X$ строит строчку $s = (s_1, s_2, \ldots, s_n)$,  где $s_k=x_1+...+x_k$, а затем выдаёт массив из построенных строчек. Используйте библиотеку <code>numpy</code> (вам поможет функция <code>cumsum</code>). Выходом функции должен быть двумерный <code>numpy</code>-массив той же формы, что и $X$.
​ 

In [15]:
def cumsum(A):
    """  
    A: np.array[num_row, num_column]        --- матрица-аргумент
    return S: np.array[num_row, num_column] --- выходная матрица кумулятивных сумм

    Функция принимает на вход матрицу A размерностью n x m и возвращает 
    матрицу с той же размерностью n x m, i-ая строчка которой есть последовательность 
    кумулятивных сумм элементов i-ой строки матрицы A

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    return np.cumsum(A, axis=1)

In [16]:
# зададим некоторую матрицу
a = np.random.randint(1, 10, size=(5, 9))
a

array([[2, 9, 5, 7, 9, 4, 6, 9, 7],
       [9, 8, 1, 8, 3, 7, 7, 6, 9],
       [3, 5, 8, 5, 2, 5, 7, 1, 4],
       [4, 6, 8, 8, 8, 4, 4, 9, 2],
       [5, 3, 8, 7, 3, 8, 1, 9, 4]])

In [17]:
%time S2 = cumsum(a)

Wall time: 0 ns


In [18]:
S2

array([[ 2, 11, 16, 23, 32, 36, 42, 51, 58],
       [ 9, 17, 18, 26, 29, 36, 43, 49, 58],
       [ 3,  8, 16, 21, 23, 28, 35, 36, 40],
       [ 4, 10, 18, 26, 34, 38, 42, 51, 53],
       [ 5,  8, 16, 23, 26, 34, 35, 44, 48]], dtype=int32)

### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив x с преобразованным x и вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [19]:
from copy import copy

def np_transformation(X, a=1):
    """  
    X: np.array[num_row, num_column]          --- матрица-аргумент
    a: float                                  --- значение для преобразования нечетных элементов строк в X
    return S: np.array[num_row, num_column*2] --- матрица, где строки являются 
    сконкатенированными строками изначальной матрицы X со строками, являющимися их преобразованиями

    Функция принимает на вход матрицу X размерностью n x m, число a и 
    возвращает  матрицу с размерностью n x m*2, i-ая строчка которой является склеенной
    i-ой строкой X с ее преобразованием ее строки transformation(X[i]), записанном в обратном порядке, 
    где преобразование для числа k определено как:
    transformation(k) = a if ind(k) % 2 == 0 else k**3

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    z = X.copy()
    z[:, 1::2] = a
    z[:, ::2] **= 3
    return np.hstack((X, z[:, ::-1]))

In [20]:
X = np.array([[i for i in range(1, 10, 2)]])
%time S2 = np_transformation(X, 5)

Wall time: 0 ns


### Задание 6
Написать функцию для кодирование массива (Run-length encoding). Все подряд идущие повторения элементов функция сжимает в один элемент и считает количество повторений этого элемента. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [21]:
from itertools import groupby

def encode_no_np(X):
    return tuple(map(np.array, zip(*[(k, len([*g])) for k, g in groupby(X)])))


def np_encode(X):
    """  
    a: np.array[, n] --- вектор-аргумент длиной n
    return (elems, repetitions): (np.array, np.array) --- выходной кортеж из вектора 
    элементов и вектора их количеств в подряд идущих повторениях

    Функция принимает на вход вектор a длиной n, добавляет в вектор elem сжатые 
    в один элемент подряд идущие повторения элементов входного вектора a, в вектор 
    repetitions добавляет длины последовательностей подряд идущих повторений. 
    Затем функция возвращает кортеж векторов (elems, repetitions).

    В реализации этой функции необходимо использовать функционал пакета numpy
    """ 
    # маска: на i-й индекс = отличается ли a[i] от a[i+1] + последний True
    mask = np.append(X[:-1] != X[1:], True)
    # индексы элементов на границах групп одинаковых чисел + первый True
    idxs = np.nonzero(np.append(True, mask))[0]
    # diff выводит приращение между индексами
    return X[mask], np.diff(idxs)

X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

In [22]:
%timeit x, num = np_encode(X)

28.3 µs ± 965 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [23]:
%timeit x, num = encode_no_np(X)

10.9 µs ± 24 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### На маленьких векторах numpy проигрывает

In [24]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3]*100)

In [25]:
%timeit x, num = np_encode(X)

37.9 µs ± 745 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [26]:
%timeit x, num = encode_no_np(X)

457 µs ± 6.94 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
