<a href="https://colab.research.google.com/github/saspav/Deep-Learning-2022/blob/main/6_1_%5Bhomework%5Dnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>


<h3 style="text-align: center;"><b>Школа глубокого обучения ФПМИ МФТИ, осень 2021</b></h3>

## Домашнее задание: библиотека Numpy и линейная алгебра


In [1]:
import numpy as np
import random
import scipy.stats as sps

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [2]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

# Выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?

# ========
# Ваш код здесь
# ========
print(a)
print(b)

[[0.18449345 0.91648011 0.51438011 ... 0.63688547 0.12676405 0.27145192]
 [0.80957903 0.24386025 0.44692211 ... 0.15359408 0.8675081  0.49324749]
 [0.06562421 0.83126661 0.45510476 ... 0.85600644 0.5886721  0.0328223 ]
 ...
 [0.64371641 0.53920908 0.55272711 ... 0.67871133 0.9634791  0.57082271]
 [0.38291381 0.87992466 0.01591399 ... 0.21287714 0.42565234 0.35262398]
 [0.04950271 0.96374356 0.40313424 ... 0.93262331 0.00968629 0.82372813]]
[[0.06874316 0.56101779 0.73818335 ... 0.44371103 0.10557128 0.03524538]
 [0.55071486 0.80452911 0.77598563 ... 0.91253815 0.51293406 0.6155841 ]
 [0.62844479 0.20678232 0.28584387 ... 0.29546374 0.75159762 0.22806946]
 ...
 [0.76000874 0.1133426  0.61965276 ... 0.19970345 0.73899659 0.87933928]
 [0.44991899 0.11352021 0.52755356 ... 0.55482311 0.82864959 0.0435958 ]
 [0.19095599 0.53201623 0.34767874 ... 0.24286937 0.56336825 0.49048754]]


In [3]:
def no_numpy_mult(a, b):
    """  
    a: list of "size" lists, each contains "size" floats --- первая матрица-аргумент
    b: list of "size" lists, each contains "size" floats --- вторая матрица-аргумент
    return c: list of "size" lists, each contains "size" floats --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц без использования функций из пакета numpy
    """
    z = len(a)
    # транспонируем матрицу b, чтобы загнать в zip
    T = [*zip(*b)]
    return [[sum(x * y for x, y in zip(a[r], T[c])) for c in range(z)] for r in range(z)]

In [4]:
def numpy_mult(a, b):
    """  
    a: np.array[size, size] --- первая матрица-аргумент
    b: np.array[size, size] --- вторая матрица-аргумент
    return c: np.array[size, size]       --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц, используя функции из пакета numpy
    """
    return a @ b

In [5]:
%%time
# засечем время работы функции без NumPy
M1 = no_numpy_mult(a, b)

CPU times: user 248 ms, sys: 4.18 ms, total: 252 ms
Wall time: 254 ms


In [6]:
%%time
# засечем время работы функции с NumPy
M2 = numpy_mult(a, b)

CPU times: user 1.88 ms, sys: 4.95 ms, total: 6.83 ms
Wall time: 9.6 ms


In [7]:
# проверим корректность
assert np.allclose(np.array(M1), M2)

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [8]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.83381158 0.13996711 0.01198492] [0.51289216 0.78356647 0.91935006]


In [9]:
def no_numpy_scalar(v1, v2):
    """  
    a: np.array[, n] --- первая матрица-аргумент длиной n
    b: np.array[, n] --- вторая матрица-аргумент длиной n
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c 

    Реализуйте скалярное умножение векторов, не используя функции из пакета numpy

    """ 
    return sum(a * b for a, b in zip(v1, v2))

In [10]:
def numpy_scalar(v1, v2):
    """  
    a: np.array[, n] --- первая матрица-аргумент
    b: np.array[, n] --- вторая матрица-аргумент
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c 

    Реализуйте скалярное умножение векторов, используя функции из пакета numpy
    """ 
    return np.dot(v1, v2)

In [11]:
%time product_1 = no_numpy_scalar(a,b)
%time product_2 = numpy_scalar(a,b)

# проверим корректность:
assert np.allclose(product_1, product_2)

CPU times: user 62 µs, sys: 11 µs, total: 73 µs
Wall time: 42 µs
CPU times: user 41 µs, sys: 7 µs, total: 48 µs
Wall time: 51.7 µs


Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональных элементов квадратной матрицы. Если таких элементов нет, то вывести `0`. Используйте библиотеку Numpy

In [12]:
def np_diag_2k(a):
    """  
    a: np.array[m, m] --- первая матрица-аргумент
    return c: float   --- сумма элементов массива а, принадлежащих диагонали и являющимися четными

    Функция принимает на вход квадратную матрицу размерностью m x m и возвращает число,
    равное сумме четных диагональных элементов этой квадратной матрицы

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    return np.diag(a)[np.diag(a) % 2 == 0].sum()

In [13]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[1, 4, 4, 4, 4],
       [9, 7, 5, 9, 4],
       [9, 5, 5, 2, 4],
       [7, 7, 5, 5, 1],
       [9, 9, 9, 8, 1]])

In [14]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 112 µs, sys: 21 µs, total: 133 µs
Wall time: 139 µs


0

### Задание 4
​
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $(x = (x_1, x_2, \ldots, x_n)$ массива $X$ строит строчку $s = (s_1, s_2, \ldots, s_n)$,  где $s_k=x_1+...+x_k$, а затем выдаёт массив из построенных строчек. Используйте библиотеку <code>numpy</code> (вам поможет функция <code>cumsum</code>). Выходом функции должен быть двумерный <code>numpy</code>-массив той же формы, что и $X$.
​ 

In [15]:
def cumsum(A):
    """  
    A: np.array[num_row, num_column]        --- матрица-аргумент
    return S: np.array[num_row, num_column] --- выходная матрица кумулятивных сумм

    Функция принимает на вход матрицу A размерностью n x m и возвращает 
    матрицу с той же размерностью n x m, i-ая строчка которой есть последовательность 
    кумулятивных сумм элементов i-ой строки матрицы A

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    return np.cumsum(A, axis=1)

In [16]:
# зададим некоторую матрицу
a = np.random.randint(1, 10, size=(5, 9))
a

array([[4, 6, 8, 4, 9, 4, 9, 8, 1],
       [8, 7, 4, 3, 8, 9, 2, 5, 3],
       [1, 6, 4, 2, 4, 7, 5, 9, 9],
       [8, 5, 5, 6, 4, 3, 2, 5, 1],
       [4, 4, 1, 9, 9, 8, 6, 3, 3]])

In [17]:
%time S2 = cumsum(a)

CPU times: user 56 µs, sys: 10 µs, total: 66 µs
Wall time: 71.5 µs


In [18]:
S2

array([[ 4, 10, 18, 22, 31, 35, 44, 52, 53],
       [ 8, 15, 19, 22, 30, 39, 41, 46, 49],
       [ 1,  7, 11, 13, 17, 24, 29, 38, 47],
       [ 8, 13, 18, 24, 28, 31, 33, 38, 39],
       [ 4,  8,  9, 18, 27, 35, 41, 44, 47]])

### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив x с преобразованным x и вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [19]:
from copy import copy

def np_transformation(X, a=1):
    """  
    X: np.array[num_row, num_column]          --- матрица-аргумент
    a: float                                  --- значение для преобразования нечетных элементов строк в X
    return S: np.array[num_row, num_column*2] --- матрица, где строки являются 
    сконкатенированными строками изначальной матрицы X со строками, являющимися их преобразованиями

    Функция принимает на вход матрицу X размерностью n x m, число a и 
    возвращает  матрицу с размерностью n x m*2, i-ая строчка которой является склеенной
    i-ой строкой X с ее преобразованием ее строки transformation(X[i]), записанном в обратном порядке, 
    где преобразование для числа k определено как:
    transformation(k) = a if ind(k) % 2 == 0 else k**3

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    z = X.copy()
    z[:, 1::2] = a
    z[:, ::2] **= 3
    return np.hstack((X, z[:, ::-1]))

In [20]:
X = np.array([[i for i in range(1, 10, 2)]])
%time S2 = np_transformation(X, 5)

CPU times: user 126 µs, sys: 0 ns, total: 126 µs
Wall time: 134 µs


### Задание 6
Написать функцию для кодирование массива (Run-length encoding). Все подряд идущие повторения элементов функция сжимает в один элемент и считает количество повторений этого элемента. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [21]:
from itertools import groupby

def encode_no_np(X):
    return tuple(map(np.array, zip(*[(k, len([*g])) for k, g in groupby(X)])))


def np_encode(X):
    """  
    a: np.array[, n] --- вектор-аргумент длиной n
    return (elems, repetitions): (np.array, np.array) --- выходной кортеж из вектора 
    элементов и вектора их количеств в подряд идущих повторениях

    Функция принимает на вход вектор a длиной n, добавляет в вектор elem сжатые 
    в один элемент подряд идущие повторения элементов входного вектора a, в вектор 
    repetitions добавляет длины последовательностей подряд идущих повторений. 
    Затем функция возвращает кортеж векторов (elems, repetitions).

    В реализации этой функции необходимо использовать функционал пакета numpy
    """ 
    # маска: на i-й индекс = отличается ли a[i] от a[i+1] + последний True
    mask = np.append(X[:-1] != X[1:], True)
    # индексы элементов на границах групп одинаковых чисел + первый True
    idxs = np.nonzero(np.append(True, mask))[0]
    # diff выводит приращение между индексами
    return X[mask], np.diff(idxs)

X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

In [22]:
%timeit x, num = np_encode(X)

26.7 µs ± 6.19 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [23]:
%timeit x, num = encode_no_np(X)

7.59 µs ± 213 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### На маленьких векторах numpy проигрывает

In [24]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3]*100)

In [25]:
%timeit x, num = np_encode(X)

26.9 µs ± 978 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [26]:
%timeit x, num = encode_no_np(X)

404 µs ± 6.18 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
